version: '3.9'
services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: flujo_dimen_db
      DB_USER: user
      DB_PASS: secret
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flujo_dimen_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./database/flujodimen_db.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "3306:3306"
