name: CI
# GitHub Actions workflow for continuous integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: Apply migrations
        run: |
          for f in database/migrations/*.sql; do
            mysql -h 127.0.0.1 -uroot -proot testing < "$f"
          done
      - name: Run tests
        run: vendor/bin/phpunit --coverage-text
  